Standardisation of datasets is a common requirement for many ML estimators implemented in sklern

In [1]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]]
)

In [2]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [4]:
X_scaled = preprocessing.scale(X_train)

In [9]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [10]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [11]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [16]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [17]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [18]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [20]:
X_test = [[-1., 1., 0.]]
scaler.transform(X_test)

array([[-2.44948974,  1.22474487, -0.26726124]])

In [21]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [22]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [23]:
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [35]:
X_test = np.array([[-3., -1.,  4.]])
X_test

array([[-3., -1.,  4.]])

In [36]:
x_test_minmax = min_max_scaler.transform(X_test)

In [37]:
x_test_minmax

array([[0., 0., 0.]])

In [38]:
min_max_scaler.scale_

array([1., 1., 1.])

In [39]:
min_max_scaler.min_

array([ 3.,  1., -4.])